[theme]
primaryColor = "#8A3FFC"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#E0E0E0"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
